### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by JoeVictor22** [JoeVictor22/cg_playground#1]
- [ ] Gerar representação com pyplot
- [ ] Definir ponto de ancoragem
- [ ] Criar métodos de transformação
